version: "3"
services:

  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME:
      MONGO_INITDB_ROOT_PASSWORD:
      MONGO_INITDB_DATABASE: recipebytes-db
    volumes:
      - "~/mongo/data:/data/db"
